### ISSUE TITLE
How to use the code 

### ISSUE THREAD

**Issue by manting12** [shreshth211/image-registration-cnn#2]
Hello! I read your paper and  try to train my data use the code  you provided. About how to train the  model using my data. I hope some suggestions or instructions. 
Your early reply would be appreciated

**Comment by kumarshreshtha** [comment]
I am sorry but I am not an author of the paper, I implemented it for a presentation. Unfortunately this code in its present state cannot be used as I never got the data access rights from NCTN/NCORP Data Archive and hence did not get a chance to complete it. I will indicate that in the readme file. However, the network architecture is completely consistent with the paper and if you know pytorch you can easily modify it to work with your data.
